mindmap
  root((DevEx))
    Feedback loops
      Perceptions
        Satisfaction with automated test speed
        Satisfaction with time it takes to validate a local change
        Satisfaction with time it takes to deploy a change to production
      Workflows
         Time it takes to generate CI results
         Code review turnaround time
         Deployment lead time
    Cognitive load
      Perceptions
        Perceived complexity of codebase
        Ease of debugging production systems
        Ease of understanding documentation
      Workflows
         Time it takes to get answers to technical questions
         Manual steps required to deploy a change
         Frequency of documentation improvements
    Flow state
      Perceptions
         Perceived ability to focus and avoid interruptions
         Satisfaction with clarity of task goals
         Perceived disruptiveness of being on-call
      Workflows
         Number of blocks of time without meetings or interruptions
         Frequency of unplanned tasks
         Frequency of incidents requiring team attention
