mindmap
  root((DORA metrics))
    Stability
    ::icon(fa fa-pager)
      Change failure rate
      Mean time to recovery
    Throughput
    ::icon(fa fa-flag-checkered)
      Deployment frequency
      Lead time to changes

