quadrantChart
    %%title DORA 
    x-axis Infrequent updates --> Frequent updates
    y-axis Low fidelity --> High fidelity
    quadrant-1 DORA Elite
    quadrant-2 DORA Gold-plated
    quadrant-3 DORA Theatre
    quadrant-4 DORA Speedrun
    GitHub: [0.9, 0.9]
    John Lewis: [0.85, 0.85]
    Accelerate: [0.05, 0.05]
    Prison wall notation: [0.6, 0.8]
    Shoestring: [0.9, 0.6]
    CircleCI: [0.6, 0.45]
    Datadog: [0.65, 0.4]
    Form-filling: [0.4, 0.75]

