mindmap
  root((SPACE))
    Satisfaction and well-being
      Individual
      Team
      System
    Performance
      Individual
      Team
      System
    Activity
      Individual
      Team
      System
    Communi-<br/>cation and collaboration
      Individual
      Team
      System
    Efficiency and flow
      Individual
      Team
      System

